/*
Palidroma Chiedere all’utente di inserire una parola Creare una funzione per capire se la parola inserita è palindroma
*/

/*
1-CHIEDERE ALL'UTENTE UNA PAROLA 
2-CREARE UNA FUNZIONA PER INVERTIRE LA PAROLA AL CONTRARIO 
3-CREARE UN IF DI VERIFICA, PER PARAGONARE LA PAROLA INIZALE CON QUELLA FINALE(INVERTITA)
4-SPAMPARE IL RISULTATO FINALE
*/